// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SonicData;

namespace SonicData.Migrations
{
    [DbContext(typeof(SSDIContext))]
    [Migration("20190320065042_Initial Migration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SonicData.Model.RequisitionRequest", b =>
                {
                    b.Property<int>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ApprovedBy");

                    b.Property<int>("DurationInMonths");

                    b.Property<int>("DurationInYears");

                    b.Property<string>("PersonToReplace");

                    b.Property<string>("PosDept");

                    b.Property<string>("PosDiv");

                    b.Property<int>("Quantity");

                    b.Property<string>("ReasonForReplacment");

                    b.Property<string>("ReqPosition");

                    b.Property<string>("RequestedBy");

                    b.Property<string>("ReviewedBy");

                    b.Property<bool>("Temporary");

                    b.HasKey("RequestId");

                    b.ToTable("RequisitionRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
